### ISSUE TITLE
启动闪退

### ISSUE THREAD

**Issue by mon030** [shizq123/BIKA#18]
设备的系统 MIUI14.0.7.0
安卓13
软件版本1.0.5
已尝试过重启设备和清除软件数据

以下是闪退log
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
	at y.b.g(SourceFile:36)
	at androidx.lifecycle.LiveData.b(Unknown Source:29)
	at androidx.lifecycle.LiveData.c(SourceFile:56)
	at androidx.lifecycle.LiveData.j(Unknown Source:14)
	at androidx.lifecycle.s.j(Unknown Source:0)
	at androidx.lifecycle.LiveData$a.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:81)
	at android.app.ActivityThread.main(Unknown Source:132)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:332)

**Comment by iwantsomeoneloveme** [comment]
我也是闪退，不清楚什么原因

**Comment by shizq123** [comment]
已解决 一会打包发布

**Comment by shizq123** [comment]
[v1.0.6](https://github.com/shizq123/BIKA/releases/tag/v1.0.6)
